# CodeRabbit configuration for Todo App React Project
# Valid configuration following CodeRabbit official schema

# Language for reviews and comments
language: en

# Review configuration
reviews:
  # Request changes workflow
  request_changes_workflow: false
  
  # High level summary
  high_level_summary: true
  
  # Poem style summary
  poem: false
  
  # Review level: chill, assertive  
  review_level: assertive
  
  # Enable/disable auto reviews
  auto_review:
    enabled: true
    
    # Auto review conditions
    drafts: false
    base_branches:
      - main
      - master
      - develop

# Path-based filters
path_filters:
  # Include patterns
  include:
    - "**/*.js"
    - "**/*.jsx" 
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.css"
    - "**/*.scss"
    - "**/*.json"
    - "**/*.md"

  # Exclude patterns  
  exclude:
    - "node_modules/**"
    - "build/**"
    - "dist/**" 
    - ".next/**"
    - "coverage/**"
    - "**/*.min.js"
    - "**/*.bundle.js"
    - "**/*.test.js"
    - "**/*.test.jsx"
    - "**/*.test.ts"
    - "**/*.test.tsx"
    - "**/*.spec.js"
    - "**/*.spec.jsx"
    - "**/*.spec.ts" 
    - "**/*.spec.tsx"

# Chat summary configuration
chat_summary:
  enabled: true

# Knowledge base
knowledge_base:
  enabled: true
  
  # Learnings from previous reviews
  learnings:
    enabled: true
  
  # Opt out of knowledge base
  opt_out: false
